name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches:
      - hugo  # 当推送到 hugo 分支时触发

  workflow_dispatch:  # 允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout hugo branch
        uses: actions/checkout@v3
        with:
          ref: hugo

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build site with Hugo
        run: hugo --minify

      - name: Deploy to GitHub Pages (master branch)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master  # ✅ 这里用 publish_branch，而不是 target_branch
          force_orphan: true
          cname: dengwq.top  # ✅ 添加这个字段，确保 CNAME 不会丢失
